labShare/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from appLabShare import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.enter, name = "enter"),
    url(r'^labShare/', include ("appLabShare.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appLabShare/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Course (models.Model):
    name = models.CharField(max_length = 128)
    level = models.PositiveSmallIntegerField ()

    def __str__ (self):
        return self.name



class UserProfile(models.Model):
    # links UserProfile to a user model instance
    # Has a username,password,email
    user = models.OneToOneField(User)

    # Boolean flag to tell us if they are a student or tutor
    status = models.CharField(max_length = 7, default = "Student")

    # Shared Tutor and Student attributes
    name = models.CharField(max_length = 128, default = "")
    picture = models.ImageField(upload_to='profile_images', default = "profile_images/user_image.png")
    bio = models.CharField(max_length = 128, default = "")
    degree = models.CharField(max_length = 128, default = "")
    university = models.CharField(max_length = 128, default = "")
    facebook = models.URLField(max_length = 300, default = "")
    instagram = models.URLField(max_length = 300, default = "")
    twitter = models.URLField(max_length = 300, default = "")
    linkedIn = models.URLField(max_length = 300, default = "")
    github = models.URLField(max_length = 300, default = "")

    # The symmetrical set to false as we do not want adding friends to add both ways
    friends = models.ManyToManyField ("self", symmetrical=False)
    courses = models.ManyToManyField (Course)

    def __str__(self):
        return self.user.username



class Lab (models.Model):
    course = models.ForeignKey (Course)

    peopleInLab = models.ManyToManyField (UserProfile)

    labNumber = models.PositiveSmallIntegerField ()

    def __str__ (self):
        # "course :: labNum"
        return self.course.__str__() + " :: " + str(self.labNumber)



class Post (models.Model):
    author = models.ForeignKey (UserProfile)
    postedIn = models.ForeignKey (Lab)
    timePosted = models.DateTimeField(default=timezone.now)
    content = models.TextField ()
    
    # Attached files will be saved to /media/lab_files/
    attachedFile = models.FileField (upload_to='lab_files', default='', blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__ (self):
        return self.content.__str__()

appLabShare/forms.py
from django import forms

from appLabShare.models import UserProfile, Post, Course


class UserProfileForm (forms.ModelForm):
    # Required form fields
    status = forms.CharField (required = True, max_length=7)
    name = forms.CharField (required = True, max_length = 128)

    # Non-required fields
    university = forms.CharField (required = False, max_length = 128)
    degree = forms.CharField (required = False, max_length = 128)
    picture = forms.ImageField (required = False)
    bio = forms.CharField (required = False, max_length = 128)
    facebook = forms.URLField(required = False, max_length = 300)
    instagram = forms.URLField(required = False, max_length = 300)
    twitter = forms.URLField(required = False, max_length = 300)
    linkedIn = forms.URLField(required = False, max_length = 300)
    github = forms.URLField(required = False, max_length = 300)


    class Meta:
        model = UserProfile
        exclude = ("user", "friends", "courses",)



class EnrolForm (forms.Form):
    course = forms.CharField (required = True, max_length=128)
    level = forms.IntegerField (required = True, min_value=1, max_value=10)
    labNumber = forms.IntegerField (required = True, min_value=1, max_value=20)



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'attachedFile')
        widgets = {
            'content' : forms.TextInput(attrs={'class' : 'commentSubmission', 'placeholder' : "Please enter a comment"}),
        }



class AddFriendForm (forms.Form):
    friend = forms.CharField (required = True)
    # Note: this form does not need a meta class (it actually breaks the form) as we are not creating
    # a model object! Simply adding to a field!

templates/labShare/addFriend.html
{% extends "labShare/loggedInBase.html" %}

{% block title_block %}
    Add a Friend!
{% endblock %}

{% block body_block %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form }}
        <p>
            <input type="submit" class="submitCommentButton" style="margin-right:20px; float: none;" value="Add Friend" name="AddFriend">
            <input type="submit" class="submitCommentButton" style="margin-right:20px; float: none;" value="Delete Friend" name="DeleteFriend">
        </p>
    </form>
    {{ error }}
{% endblock %}

templates/labShare/enrol.html
{% extends "labShare/loggedInBase.html" %}

{% block title_block %}
    Enrol
{% endblock %}

{% block body_block %}
  <div class="box" style="margin-top: -120px; margin-bottom: 10px; border-radius:50%">
  Enrol
  </div>

  <script type="text/javascript">colour_randomiser(".box")</script>

  <p style="color: red">{{ error }}</p>

  <p>
    You can enrol in the courses below.<br>
    You may have been redirected to this page if you tried
    to access a lab you are not enrolled in. <br>
    If you are a student then you can only enrol in 1 lab
    per course (enrolling in a lab of a course you are already enrolled in will remove you from
    the lab you are currently in). <br>
    If you are a tutor then you can be enrolled in as many labs as
    you wish and you can also create labs and courses by enrolling in a lab that has not been created
    yet (Please use the course code where possible).
  </p>


  <div class="enroll">
    <form action="/labShare/enrol/" method="post">
        {% csrf_token %}

        <p style="display: inline-block;">
        Course:
        <input type="text" class="commentSubmission" name="course" style="margin: 5%; padding: 15px;"maxlength="128" required="" id="enrollButtons" placeholder="Course Name">
        </p>

        <p style="display: inline-block;">
        Level:
        <input type="number" class="commentSubmission" name="level" style="margin: 5%; padding: 15px;" min="1" max="5" required="" id="enrollButtons" placeholder = "Level">
        </p>

        <p style="display: inline-block;">
        Lab Number:
        <input type="number" class="commentSubmission" name="labNumber" style="margin: 5%; padding: 15px; width:63%; text-align:center;"min="1" max="20" required="" id="enrollButtons" placeholder="Lab Number">
        </p>
        <br>

        <!-- Enrol/Unenrol buttons -->
        <input type="submit" style="display: inline-block; margin-right: 0px; float:none;" class="submitCommentButton" id="enrollButton" value="Enrol" name="enrol">
        <input type="submit" style="display: inline-block; margin-right: 0px; float:none;" class="submitCommentButton" id="enrollButton" value="Unenrol" name="unenrol">
        <br>

        <hr style="margin-top:10%; width: 60%;">
    </form>
  </div>


    <br>
    <div class="section">

    <div class="table" style="overflow-x:auto;">
      <table cellpadding = "20">
        <tr class="row">
          <th class="column">  Course Level</th>
          <th class="column">  Course Name</th>
          <th class="column">  Lab Numbers</th>
        </tr>

        {% for courseLab in table %}
          <tr>
            <td>{{ courseLab.0.level }}</td>
            <td>{{ courseLab.0.name }}</td>
            <td>
              {% for lab in courseLab.1 %}
                {{ lab.labNumber }}
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock %}

templates/labShare/enter.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Welcome to Labshare!</title>
    
    <link rel="shortcut icon" type="image/png" href="{% static "images/favicon.png" %}" sizes="16x2"/>
    <link rel="stylesheet" type="text/css" href="{% static "CSS/enter.css"%}" />
    <img src="{% static 'images/logo.png' %}" alt="logo" class = "logo">

    <div class="logo"></div>
  </head>

  <body>
    <div class="wrapper">
      <p style="font-family: Arial; font-size: 60px; font-weight:700; color: rgb(33, 33, 33)"> Welcome to Labshare! </p>
      <a href="{% url 'auth_login' %}" style="text-decoration:none;"><span class="text1"> Enter </span></a>
    </div>
  </body>
</html>

templates/labShare/friendsList.html
{% extends "labShare/loggedInBase.html" %}
{% load staticfiles %}

<div class="profilePicture">
{% block picture %}{{ MEDIA_URL }}{{ profile.picture }}{% endblock %}
</div>
{% block body_block %}
  <h1>{{profile.name}}'s friends</h1>
  <hr style="width:80%">

  {% if not profile.friends.all %}
    <h2>This user has no friends!</h2>
  {% endif %}

  <div class="bodyDiv">
    {% for friend in profile.friends.all %}
        <div class="card">
          <div class="cardImage">
            <a href="{% url 'profile' friend.user.username %}">

            <img src="{{ MEDIA_URL }}{{ friend.picture }}" alt="{{ friend.name }}'s picture">
          </div>
          <div class="details">
            <div class="center">

              <h1 class="friendDetails" style="text-decoration:none;">{{ friend.name }} <br> <span class="friendDetails" style="text-decoration:none;"> {{ friend.status }} </span> </h1>
              <p class="friendDetails" style="text-decoration:none;" >{{ friend.bio }}</p>
              </a>
              <ul>
                {% if friend.github != "" %}
                  <li id="github"><a href="{{ friend.github }}"><i class="fab fa-github" aria-hidden="true"></i></a></li>
                {% endif %}
                {% if friend.facebook != "" %}
                  <li id="facebook"><a href="{{ friend.facebook }}"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                {% endif %}
                {% if friend.twitter != "" %}
                  <li id="twitter" ><a href="{{ friend.twitter }}"><i class= "fab fa-twitter" aria-hidden="true"></i></a></li>
                {% endif %}
                {% if friend.linkedIn != "" %}
                  <li id="linkedin" ><a href="{{ friend.linkedIn}}"><i class="fab fa-linkedin-in" aria-hidden="true"></i></a></li>
                {% endif %}
                {% if friend.instagram != "" %}
                  <li id="instagram" ><a href="{{ friend.instagram }}"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
    {% endfor %}

    <script type="text/javascript">colour_randomiser(".details")</script>

    {% if pageUser == user %}
    <a href="{% url 'addFriend' %}">
      <h3><font color="FFFFFF">Add or delete a friend</font></h3>
    </a>
    {% endif %}
  </div>
{% endblock %}

templates/labShare/lab.html
{% extends "labShare/loggedInBase.html" %}

{% block title_block %}
  {{ lab.course.name }} - Lab {{ lab.labNumber }}
{% endblock %}

<!-- This is a work in progress and can be ignored -->
<!-- People in Labs - Sidebar -->
{% block sidebar_block %}
  {% for user in lab.peopleInLab.all %}
    <!-- <h1>{{ user }}</h1> -->
  {% endfor %}
{% endblock %}

{% block body_block %}
  <div class="box" style="margin-top: -120px; border-radius:50%">
    {{ lab.course.name }}
    Lab {{ lab.labNumber }}
  </div>

  <!-- Javascript for the "Lab X" circle -->
  <script type="text/javascript">colour_randomiser(".box");</script>

  <!-- List of users in the lab -->
  <div class="userList" >
    <!-- Tutors -->
    <div class="tutorList" style=" clear: both; float:none; text-align:center; margin: 0; padding: 0; display: inline-block; ">
      <strong><p style="font-size: 35px; letter-spaceing: 6px;">Tutors: </p style="text-align:center"></strong>
      {% for person in lab.peopleInLab.all %}
        {% if person.status == "Tutor" %}
          <ul style="text-align: left;">
            <li style="text-align: left;text-decoration: none; display: inline-block; font-size: 25px; letter-spaceing: 6px;">  {{ person }} </li>
          </ul>
        {% endif %}
      {% endfor %}
    </div>
  </div>

  <!-- Comment submission -->
  <form style="clear:both;" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Comment text input -->
    <p>
      <textarea name="content" required="True" id="id_content" class="commentSubmission" placeholder='Please enter a comment'></textarea>
      <!-- Submit Button -->
      <input type="submit" value="Submit Comment" class="submitCommentButton">
    </p>

    <!-- File upload -->
    <p style="margin-top:10px;">
      Upload File:
      <input type="file" name="attachedFile" onchange="previewFile()" id="id_file">
    </p>

  </form>

  <!-- Visual line break between comment submission and comments -->
  <hr style="margin-top:0%; width: 80%;">


  <!-- The following displays all the comments in a discussion page -->
  {% for post in posts %}
    <div class="comment">
      <img id="commentUserImage" src="{{ MEDIA_URL }}{{ post.author.picture }}" alt="User Image"/>
      <p style="color:#4cffff">{{ post.author.name }} • {{ post.author }} • {{ post.timePosted }}</p>
      <h3>{{ post.content }}</h3>
      <p><a href="{{ MEDIA_URL }}{{ post.attachedFile }}" style="color: #5e9bff">{{ post.attachedFile }}</a></p>
    </div>
  {% endfor %}

{% endblock %}

templates/labShare/labList.html
{% extends 'labShare/loggedInBase.html' %}

<div class="profilePicture">
  {% block picture %}{{ MEDIA_URL }}{{ profile.picture }}{% endblock %}
</div>

{% block body_block %}
  <div class="name">
    <h3 class="gradient-text" style="font-family: "Dosis"">{{profile.name}}'s Labs</h3>
  </div>

  <p class="text" style="margin-bottom:15px; text-align:center;">{{ profile.degree }}</p>

  <hr>

    <div class="labListItems">
        {% for lab in labs %}
          <a href="{% url 'lab' lab.course.name lab.labNumber %}"><span><div class="box" style="opacity: .7;">{{ lab.course.name }} - {{ lab.labNumber }}</div><span></a>
        {% endfor %}

        {% if not labs %}
          <p style="font-size: 40px;">This user is not enrolled in any labs!</p>
        {% endif %}

        {% if user == pageUser %}
          <a href="{% url 'enrol' %}"><span><div class="box" style="opacity: .7;" id="add"> +/- </div></span></a>
        {% endif %}
    </div>
  <!-- Colour randomiser from list -->
  <script type="text/javascript">colour_randomiser(".box");</script>

  <hr style="margin-top:10%;">

{% endblock %}

templates/labShare/loggedInBase.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8" lang="en">

    <link rel="shortcut icon" type="image/png" href="{% static "images/favicon.png" %}" sizes="16x2"/>
    <link rel="stylesheet" href="{% static "CSS/main.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Asap|Comfortaa|Dosis|Maven+Pro|Muli|Poppins|Quicksand|Rubik" rel="stylesheet">

    <script type="text/javascript" src="{% static "javascript/script.js" %}"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <title>
      LabShare -
      {% block title_block %}
        Sharing your labs with friends!
      {% endblock %}
    </title>
  </head>

  <body>
    <nav>
        {% url 'register-profile' as no_nav %}
        {% url 'register' as no_nav2 %}
        {% if request.get_full_path != no_nav and request.get_full_path != no_nav2 %}
        {% if user.is_authenticated %}
          <a href="{% url 'profile' user.username %}"><img class="logo" src="{% static "images/logo.png" %}" alt="logo" draggable="false" width="330" height="100"> </a>
        {% else %}
          <img class="logo" src="{% static "images/logo.png" %}" alt="logo" draggable="false" width="330" height="100">
        {% endif %}
            {% if user.is_authenticated %}
                <ul>
                  <li id= "linkRef"><a href="{% url 'labList' user.username %}" id="link"><i class="fas fa-flask" class="labsButton"></i> My Labs</a></li>
                  <li id= "linkRef"><a href="{% url 'profile' user.username %}" id="link"><i class="far fa-user"></i>  My Profile</a></li>
                  <li id= "linkRef"><a href="{% url 'friendsList' user.username %}" id="link"> <i class="fas fa-users"></i>  My Friends</a></li>
                  <li id= "linkRef"><a href="{% url 'auth_logout' %}?next=/labShare/" id="link"><i class="fas fa-sign-out-alt"></i>  Sign Out</a></li>
                </ul>
            {% endif %}
        {% else %}
            <a href="{% url 'enter' %}">
            <img class="logo" src="{% static "images/logo.png" %}" alt="logo" draggable="false" width="330" height="100">
            </a>
        {% endif %}
      <div style="clear:both;"></div>
    </nav>

    <div class="responsive-bar" style="border-bottom: 3px solid #fff;">
      <img  src="{% static "images/logo.png" %}" alt="logo" draggable="false" width="330" height="100">
      {% if user.is_authenticated %}
      <button class="purpleButton"><i class="fa fa-bars" aria-hidden="true"> </i></button>
      {% endif %}
      <div style="clear: both;"></div>
    </div>

    <script type="text/javascript">navbar_button();</script>

    <div class="container">
      <!-- NOTE: I have changed this to be dynamic so I can dynamically use profile pictures
                 Use the block in extending templates with the path to include a picture -->
      {% url 'profile' pageUser.username as the_url %}
      {% url 'labList' user.username as the_url2 %}
      {% url 'friendsList' user.username as the_url3 %}
      {% if request.get_full_path == the_url or request.get_full_path == the_url2 or request.get_full_path == the_url3 %}
        <img src="{% block picture %}{% endblock %}" draggable="false">
      {% endif %}

      <div>
        {% block sidebar_block %}
        {% endblock %}
      </div>

      <div class="elements">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

templates/labShare/profile.html
{% extends "labShare/loggedInBase.html" %}
{% block title_block %}
    My Profile
{% endblock %}

<div class="profilePicture">
{% block picture %}{{ MEDIA_URL }}{{ profile.picture }}{% endblock %}
</div>

{% block body_block %}
  <div class="grid">
    <div class="mainSection">
      <div class="name">{{profile.name}}</div>
      <div class="status">{{profile.status}} - {{ profile.user.username}}</div>
      <div class="email">{{profile.user.email}}</div>
      <div class="bio"><p>{{profile.bio}}</p></div>
      <div class="degree"> <p>{{profile.degree}}</p></div>
      <div class="uni"> <p>{{profile.university}}</p></div>
      <div class="editProfileButton">
        {% if pageUser == user %}
          <a href="{% url 'edit_profile' %}"> <button class="btn" type="button" name="button">  <i class="fas fa-edit"></i> Edit Profile </button> </a>
        {% endif %}
      </div>
    </div>
    <div class="friendsSection">
      <div class="friends"> <span> Friends List </span> </div>
      <ul>
        {% if not profile.friends.all %}
          <li>This user does not have any friends!</li>
        {% endif %}
        {% for friend in profile.friends.all %}
          <li>{{ friend.user.username }} - {{ friend.name }}</li>
        {% endfor %}
      </ul>
      <div class="friendsButton">
        <a href="{% url 'friendsList' pageUser.username %}"> <button class="btn" type="button" name="button">    <i class="fas fa-users"></i> Friends </button> </a>
      </div>
    </div>
    <div class="labsSection">
      <div class="labs"> <span> Courses </span> </div>
      <ul>
        {% if not profile.courses.all %}
          <li>This user is not enrolled in any courses!</li>
        {% endif %}
        {% for course in profile.courses.all %}
          <li>{{ course.name }}</li>
        {% endfor %}
      </ul>
      <div class="labsButton">
        <a href="{% url 'labList' pageUser.username %}"> <button class="btn" type="button" name="button"><i class="fas fa-flask" class="labsButton"></i> Labs </button> </a>
      </div>
    </div>
    <div class="socialMediaSection">
      <div class="links"> <span>Links</span></div>
      {% if not hasLinks %}
        <p style="margin-left:45px;" class="hasNoLinks">This user has no social media links!</p>
      {% endif %}
        <ul>
              {% if profile.github != "" %}
                <li id="github"><a href="{{ profile.github }}"><i class="fab fa-github" aria-hidden="true"></i></a></li>
              {% endif %}

              {% if profile.facebook != "" %}
                <li id="facebook"><a href="{{ profile.facebook }}"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
              {% endif %}

              {% if profile.twitter != "" %}
                <li id="twitter" ><a href="{{ profile.twitter }}"><i class= "fab fa-twitter" aria-hidden="true"></i></a></li>
              {% endif %}

              {% if profile.linkedIn != "" %}
                <li id="linkedin" ><a href="{{ profile.linkedIn}}"><i class="fab fa-linkedin-in" aria-hidden="true"></i></a></li>
              {% endif %}

              {% if profile.instagram != "" %}
                <li id="instagram" ><a href="{{ profile.instagram }}"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
              {% endif %}
        </ul>
  </div>
{% endblock %}

templates/labShare/setup_profile.html
{% extends "labShare/loggedInBase.html" %}
{% load staticfiles %}

{% block title_block %}
    Profile Information
{% endblock %}

{% block body_block %}
    <h1>Add some personal information for your profile!</h1>
    {% if form.errors %}
      <h4>Please ammend the following fields:</h4>
      <ul class="form-errors" style="float:none;padding-right:25px;">
    {% for error in form.errors %}
        <li style="color:white; list-style-type:none;">{{ error }}</li>
    {% endfor %}
      </ul>
    {% endif %}

    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <p>
          <label for="id_status">Position:</label><br>
          <select class="setup_dropdown" name="status">
            <option value="Student">Student</option>
            <option value="Tutor">Tutor</option>
          </select>
        </p>

        <p>
           <label for="id_name">Name:</label><br>
           <input type="text" name="name" maxlength="128" required="" id="id_name" class="setup_profile">
         </p>

        <p>
          <label for="id_picture">Picture:</label><br>
           <input type="file" name="picture" onchange="previewFile()" id="id_picture" style="margin-top:10px;"><br>
           <img id="blah" src="#" alt="your image" onerror="this.src='{% static "images/user_image.png" %}'"/>
         </p>

        <p>
          <label for="id_bio">Bio:</label><br>
           <textarea name="bio" id="id_bio" class="setup_bio" rows="10" tabindex="4"></textarea>
         </p>

        <p>
          <label for="id_degree">Degree:</label><br>
           <input type="text" name="degree" maxlength="128" id="id_degree" class="setup_profile">
         </p>

        <p>
          <label for="id_university">University:</label><br>
           <input type="text" name="university" maxlength="128" id="id_university" class="setup_profile">
         </p>

         <h2>If you want to include any social media links do so below!</h2>
         
         <p>
             <label for="id_facebook">Facebook:</label><br>
             <input type="text" name="facebook" maxlength="300" id="id_facebook" class="setup_profile">
         </p>
         <p>
             <label for="id_instagram">Instagram:</label><br>
             <input type="text" name="instagram" maxlength="300" id="id_instagram" class="setup_profile">
         </p>
         <p>
             <label for="id_twitter">Twitter:</label><br>
             <input type="text" name="twitter" maxlength="300" id="id_twitter" class="setup_profile">
         </p>
         <p>
             <label for="id_linkedIn">LinkedIn:</label><br>
             <input type="text" name="linkedIn" maxlength="300" id="id_linkedIn" class="setup_profile">
         </p>
         <p>
             <label for="id_github">Github:</label><br>
             <input type="text" name="github" maxlength="300" id="id_github" class="setup_profile">
         </p>

        <input type="submit" value="Submit">
    </form>
{% endblock %}